/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export enum CurrIndex { Below, Inside, Above };

export type CurrIndexArgs = CurrIndex;

export function getCurrIndexEncoder(): FixedSizeEncoder<CurrIndexArgs> {
    return getEnumEncoder(CurrIndex);
}

export function getCurrIndexDecoder(): FixedSizeDecoder<CurrIndex> {
    return getEnumDecoder(CurrIndex);
}

export function getCurrIndexCodec(): FixedSizeCodec<CurrIndexArgs, CurrIndex> {
    return combineCodec(getCurrIndexEncoder(), getCurrIndexDecoder());
}