/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export enum TickLabel { Upper, Lower };

export type TickLabelArgs = TickLabel;

export function getTickLabelEncoder(): FixedSizeEncoder<TickLabelArgs> {
    return getEnumEncoder(TickLabel);
}

export function getTickLabelDecoder(): FixedSizeDecoder<TickLabel> {
    return getEnumDecoder(TickLabel);
}

export function getTickLabelCodec(): FixedSizeCodec<TickLabelArgs, TickLabel> {
    return combineCodec(getTickLabelEncoder(), getTickLabelDecoder());
}