/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export enum RewardState { Uninitialized, Initialized, Opening, Ended };

export type RewardStateArgs = RewardState;

export function getRewardStateEncoder(): FixedSizeEncoder<RewardStateArgs> {
    return getEnumEncoder(RewardState);
}

export function getRewardStateDecoder(): FixedSizeDecoder<RewardState> {
    return getEnumDecoder(RewardState);
}

export function getRewardStateCodec(): FixedSizeCodec<RewardStateArgs, RewardState> {
    return combineCodec(getRewardStateEncoder(), getRewardStateDecoder());
}