name: Checkout Repository + Configure Git
description: Checkout the repo branch with GitHub App credentials, allowing bypassing branch protection rules to bump versions

inputs:
  enforce_master:
    description: 'Enforce master branch checked out'
    default: 'true'

runs:
  using: composite
  steps:
    - name: Assert App Secrets Env Set
      shell: bash
      run: |
        test -n "${{ env.GH_APP_ID }}" || (echo "GH_APP_ID missing" && exit 1)
        test -n "${{ env.GH_APP_PRIVATE_KEY }}" || (echo "GH_APP_PRIVATE_KEY missing" && exit 1)

    - name: Create GitHub App token
      id: app-token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
      with:
        app-id: ${{ env.GH_APP_ID }}
        private-key: ${{ env.GH_APP_PRIVATE_KEY }}

    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}

    - name: Ensure on master branch
      if: ${{ inputs.enforce_master != 'false' }}
      shell: bash
      run: |
        if [ "${GITHUB_REF_NAME}" != "master" ]; then
          echo "Must be on master branch to publish the package."
          exit 1
        fi

    - name: Configure Git User
      shell: bash
      run: |
        git config user.name "kmno-release[bot]"
        git config user.email "kmno-release[bot]@users.noreply.github.com"
