/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export enum CreationStatus { IGNORED, SHADOW, LIVE, DEPRECATED, STAGING };

export type CreationStatusArgs = CreationStatus;

export function getCreationStatusEncoder(): FixedSizeEncoder<CreationStatusArgs> {
    return getEnumEncoder(CreationStatus);
}

export function getCreationStatusDecoder(): FixedSizeDecoder<CreationStatus> {
    return getEnumDecoder(CreationStatus);
}

export function getCreationStatusCodec(): FixedSizeCodec<CreationStatusArgs, CreationStatus> {
    return combineCodec(getCreationStatusEncoder(), getCreationStatusDecoder());
}