/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export enum ExecutiveWithdrawAction { Freeze, Unfreeze, Rebalance };

export type ExecutiveWithdrawActionArgs = ExecutiveWithdrawAction;

export function getExecutiveWithdrawActionEncoder(): FixedSizeEncoder<ExecutiveWithdrawActionArgs> {
    return getEnumEncoder(ExecutiveWithdrawAction);
}

export function getExecutiveWithdrawActionDecoder(): FixedSizeDecoder<ExecutiveWithdrawAction> {
    return getEnumDecoder(ExecutiveWithdrawAction);
}

export function getExecutiveWithdrawActionCodec(): FixedSizeCodec<ExecutiveWithdrawActionArgs, ExecutiveWithdrawAction> {
    return combineCodec(getExecutiveWithdrawActionEncoder(), getExecutiveWithdrawActionDecoder());
}