/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getStructDecoder, getStructEncoder, getU128Decoder, getU128Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export type RebalancePricePercentageWithResetState = { lastRebalanceLowerResetPoolPrice: bigint; lastRebalanceUpperResetPoolPrice: bigint;  };

export type RebalancePricePercentageWithResetStateArgs = { lastRebalanceLowerResetPoolPrice: number | bigint; lastRebalanceUpperResetPoolPrice: number | bigint;  };

export function getRebalancePricePercentageWithResetStateEncoder(): FixedSizeEncoder<RebalancePricePercentageWithResetStateArgs> {
    return getStructEncoder([['lastRebalanceLowerResetPoolPrice', getU128Encoder()], ['lastRebalanceUpperResetPoolPrice', getU128Encoder()]]);
}

export function getRebalancePricePercentageWithResetStateDecoder(): FixedSizeDecoder<RebalancePricePercentageWithResetState> {
    return getStructDecoder([['lastRebalanceLowerResetPoolPrice', getU128Decoder()], ['lastRebalanceUpperResetPoolPrice', getU128Decoder()]]);
}

export function getRebalancePricePercentageWithResetStateCodec(): FixedSizeCodec<RebalancePricePercentageWithResetStateArgs, RebalancePricePercentageWithResetState> {
    return combineCodec(getRebalancePricePercentageWithResetStateEncoder(), getRebalancePricePercentageWithResetStateDecoder());
}