/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU16Decoder, getU16Encoder, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '../../_shims/programClientCore';
import { YVAULTS_PROGRAM_ADDRESS } from '../programs';

const SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS = 7340032 as const;

export const UPDATE_TREASURY_FEE_VAULT_DISCRIMINATOR = new Uint8Array([9, 241, 94, 91, 173, 74, 166, 119]);

export function getUpdateTreasuryFeeVaultDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(UPDATE_TREASURY_FEE_VAULT_DISCRIMINATOR); }

export type UpdateTreasuryFeeVaultInstruction<TProgram extends string = typeof YVAULTS_PROGRAM_ADDRESS, TAccountSigner extends string | AccountMeta<string> = string, TAccountGlobalConfig extends string | AccountMeta<string> = string, TAccountFeeMint extends string | AccountMeta<string> = string, TAccountTreasuryFeeVault extends string | AccountMeta<string> = string, TAccountTreasuryFeeVaultAuthority extends string | AccountMeta<string> = string, TAccountTokenInfos extends string | AccountMeta<string> = string, TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111", TAccountRent extends string | AccountMeta<string> = "SysvarRent111111111111111111111111111111111", TAccountTokenProgram extends string | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSigner extends string ? WritableSignerAccount<TAccountSigner> & AccountSignerMeta<TAccountSigner> : TAccountSigner, TAccountGlobalConfig extends string ? WritableAccount<TAccountGlobalConfig> : TAccountGlobalConfig, TAccountFeeMint extends string ? ReadonlyAccount<TAccountFeeMint> : TAccountFeeMint, TAccountTreasuryFeeVault extends string ? WritableAccount<TAccountTreasuryFeeVault> : TAccountTreasuryFeeVault, TAccountTreasuryFeeVaultAuthority extends string ? ReadonlyAccount<TAccountTreasuryFeeVaultAuthority> : TAccountTreasuryFeeVaultAuthority, TAccountTokenInfos extends string ? ReadonlyAccount<TAccountTokenInfos> : TAccountTokenInfos, TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram, TAccountRent extends string ? ReadonlyAccount<TAccountRent> : TAccountRent, TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram, ...TRemainingAccounts]>;

export type UpdateTreasuryFeeVaultInstructionData = { discriminator: ReadonlyUint8Array; collateralId: number;  };

export type UpdateTreasuryFeeVaultInstructionDataArgs = { collateralId: number;  };

export function getUpdateTreasuryFeeVaultInstructionDataEncoder(): FixedSizeEncoder<UpdateTreasuryFeeVaultInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['collateralId', getU16Encoder()]]), (value) => ({ ...value, discriminator: UPDATE_TREASURY_FEE_VAULT_DISCRIMINATOR }));
}

export function getUpdateTreasuryFeeVaultInstructionDataDecoder(): FixedSizeDecoder<UpdateTreasuryFeeVaultInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['collateralId', getU16Decoder()]]);
}

export function getUpdateTreasuryFeeVaultInstructionDataCodec(): FixedSizeCodec<UpdateTreasuryFeeVaultInstructionDataArgs, UpdateTreasuryFeeVaultInstructionData> {
    return combineCodec(getUpdateTreasuryFeeVaultInstructionDataEncoder(), getUpdateTreasuryFeeVaultInstructionDataDecoder());
}

export type UpdateTreasuryFeeVaultInput<TAccountSigner extends string = string, TAccountGlobalConfig extends string = string, TAccountFeeMint extends string = string, TAccountTreasuryFeeVault extends string = string, TAccountTreasuryFeeVaultAuthority extends string = string, TAccountTokenInfos extends string = string, TAccountSystemProgram extends string = string, TAccountRent extends string = string, TAccountTokenProgram extends string = string> =  {
  signer: TransactionSigner<TAccountSigner>;
globalConfig: Address<TAccountGlobalConfig>;
feeMint: Address<TAccountFeeMint>;
treasuryFeeVault: Address<TAccountTreasuryFeeVault>;
treasuryFeeVaultAuthority: Address<TAccountTreasuryFeeVaultAuthority>;
tokenInfos: Address<TAccountTokenInfos>;
systemProgram?: Address<TAccountSystemProgram>;
rent?: Address<TAccountRent>;
tokenProgram?: Address<TAccountTokenProgram>;
collateralId: UpdateTreasuryFeeVaultInstructionDataArgs["collateralId"];
}

export function getUpdateTreasuryFeeVaultInstruction<TAccountSigner extends string, TAccountGlobalConfig extends string, TAccountFeeMint extends string, TAccountTreasuryFeeVault extends string, TAccountTreasuryFeeVaultAuthority extends string, TAccountTokenInfos extends string, TAccountSystemProgram extends string, TAccountRent extends string, TAccountTokenProgram extends string, TProgramAddress extends Address = typeof YVAULTS_PROGRAM_ADDRESS>(input: UpdateTreasuryFeeVaultInput<TAccountSigner, TAccountGlobalConfig, TAccountFeeMint, TAccountTreasuryFeeVault, TAccountTreasuryFeeVaultAuthority, TAccountTokenInfos, TAccountSystemProgram, TAccountRent, TAccountTokenProgram>, config?: { programAddress?: TProgramAddress } ): UpdateTreasuryFeeVaultInstruction<TProgramAddress, TAccountSigner, TAccountGlobalConfig, TAccountFeeMint, TAccountTreasuryFeeVault, TAccountTreasuryFeeVaultAuthority, TAccountTokenInfos, TAccountSystemProgram, TAccountRent, TAccountTokenProgram> {
  // Program address.
const programAddress = config?.programAddress ?? YVAULTS_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { signer: { value: input.signer ?? null, isWritable: true }, globalConfig: { value: input.globalConfig ?? null, isWritable: true }, feeMint: { value: input.feeMint ?? null, isWritable: false }, treasuryFeeVault: { value: input.treasuryFeeVault ?? null, isWritable: true }, treasuryFeeVaultAuthority: { value: input.treasuryFeeVaultAuthority ?? null, isWritable: false }, tokenInfos: { value: input.tokenInfos ?? null, isWritable: false }, systemProgram: { value: input.systemProgram ?? null, isWritable: false }, rent: { value: input.rent ?? null, isWritable: false }, tokenProgram: { value: input.tokenProgram ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}
if (!accounts.rent.value) {
accounts.rent.value = 'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
}
if (!accounts.tokenProgram.value) {
accounts.tokenProgram.value = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
}

const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta("signer", accounts.signer), getAccountMeta("globalConfig", accounts.globalConfig), getAccountMeta("feeMint", accounts.feeMint), getAccountMeta("treasuryFeeVault", accounts.treasuryFeeVault), getAccountMeta("treasuryFeeVaultAuthority", accounts.treasuryFeeVaultAuthority), getAccountMeta("tokenInfos", accounts.tokenInfos), getAccountMeta("systemProgram", accounts.systemProgram), getAccountMeta("rent", accounts.rent), getAccountMeta("tokenProgram", accounts.tokenProgram)], data: getUpdateTreasuryFeeVaultInstructionDataEncoder().encode(args as UpdateTreasuryFeeVaultInstructionDataArgs), programAddress } as UpdateTreasuryFeeVaultInstruction<TProgramAddress, TAccountSigner, TAccountGlobalConfig, TAccountFeeMint, TAccountTreasuryFeeVault, TAccountTreasuryFeeVaultAuthority, TAccountTokenInfos, TAccountSystemProgram, TAccountRent, TAccountTokenProgram>);
}

export type ParsedUpdateTreasuryFeeVaultInstruction<TProgram extends string = typeof YVAULTS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
signer: TAccountMetas[0];
globalConfig: TAccountMetas[1];
feeMint: TAccountMetas[2];
treasuryFeeVault: TAccountMetas[3];
treasuryFeeVaultAuthority: TAccountMetas[4];
tokenInfos: TAccountMetas[5];
systemProgram: TAccountMetas[6];
rent: TAccountMetas[7];
tokenProgram: TAccountMetas[8];
};
data: UpdateTreasuryFeeVaultInstructionData; };

export function parseUpdateTreasuryFeeVaultInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedUpdateTreasuryFeeVaultInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
  throw new Error(`Program client error: ${JSON.stringify({ actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 9 })}`);
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { signer: getNextAccount(), globalConfig: getNextAccount(), feeMint: getNextAccount(), treasuryFeeVault: getNextAccount(), treasuryFeeVaultAuthority: getNextAccount(), tokenInfos: getNextAccount(), systemProgram: getNextAccount(), rent: getNextAccount(), tokenProgram: getNextAccount() }, data: getUpdateTreasuryFeeVaultInstructionDataDecoder().decode(instruction.data) };
}