/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { addDecoderSizePrefix, addEncoderSizePrefix, combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU32Decoder, getU32Encoder, getUtf8Decoder, getUtf8Encoder, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type Codec, type Decoder, type Encoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '../../_shims/programClientCore';
import { YVAULTS_PROGRAM_ADDRESS } from '../programs';

const SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS = 7340032 as const;

export const UPDATE_SHARES_METADATA_DISCRIMINATOR = new Uint8Array([155, 34, 122, 165, 245, 137, 147, 107]);

export function getUpdateSharesMetadataDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(UPDATE_SHARES_METADATA_DISCRIMINATOR); }

export type UpdateSharesMetadataInstruction<TProgram extends string = typeof YVAULTS_PROGRAM_ADDRESS, TAccountAdminAuthority extends string | AccountMeta<string> = string, TAccountStrategy extends string | AccountMeta<string> = string, TAccountGlobalConfig extends string | AccountMeta<string> = string, TAccountSharesMint extends string | AccountMeta<string> = string, TAccountSharesMetadata extends string | AccountMeta<string> = string, TAccountSharesMintAuthority extends string | AccountMeta<string> = string, TAccountMetadataProgram extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountAdminAuthority extends string ? WritableSignerAccount<TAccountAdminAuthority> & AccountSignerMeta<TAccountAdminAuthority> : TAccountAdminAuthority, TAccountStrategy extends string ? ReadonlyAccount<TAccountStrategy> : TAccountStrategy, TAccountGlobalConfig extends string ? ReadonlyAccount<TAccountGlobalConfig> : TAccountGlobalConfig, TAccountSharesMint extends string ? ReadonlyAccount<TAccountSharesMint> : TAccountSharesMint, TAccountSharesMetadata extends string ? WritableAccount<TAccountSharesMetadata> : TAccountSharesMetadata, TAccountSharesMintAuthority extends string ? ReadonlyAccount<TAccountSharesMintAuthority> : TAccountSharesMintAuthority, TAccountMetadataProgram extends string ? ReadonlyAccount<TAccountMetadataProgram> : TAccountMetadataProgram, ...TRemainingAccounts]>;

export type UpdateSharesMetadataInstructionData = { discriminator: ReadonlyUint8Array; name: string; symbol: string; uri: string;  };

export type UpdateSharesMetadataInstructionDataArgs = { name: string; symbol: string; uri: string;  };

export function getUpdateSharesMetadataInstructionDataEncoder(): Encoder<UpdateSharesMetadataInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['name', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())], ['symbol', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())], ['uri', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())]]), (value) => ({ ...value, discriminator: UPDATE_SHARES_METADATA_DISCRIMINATOR }));
}

export function getUpdateSharesMetadataInstructionDataDecoder(): Decoder<UpdateSharesMetadataInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['name', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())], ['symbol', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())], ['uri', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())]]);
}

export function getUpdateSharesMetadataInstructionDataCodec(): Codec<UpdateSharesMetadataInstructionDataArgs, UpdateSharesMetadataInstructionData> {
    return combineCodec(getUpdateSharesMetadataInstructionDataEncoder(), getUpdateSharesMetadataInstructionDataDecoder());
}

export type UpdateSharesMetadataInput<TAccountAdminAuthority extends string = string, TAccountStrategy extends string = string, TAccountGlobalConfig extends string = string, TAccountSharesMint extends string = string, TAccountSharesMetadata extends string = string, TAccountSharesMintAuthority extends string = string, TAccountMetadataProgram extends string = string> =  {
  adminAuthority: TransactionSigner<TAccountAdminAuthority>;
strategy: Address<TAccountStrategy>;
globalConfig: Address<TAccountGlobalConfig>;
sharesMint: Address<TAccountSharesMint>;
sharesMetadata: Address<TAccountSharesMetadata>;
sharesMintAuthority: Address<TAccountSharesMintAuthority>;
metadataProgram: Address<TAccountMetadataProgram>;
name: UpdateSharesMetadataInstructionDataArgs["name"];
symbol: UpdateSharesMetadataInstructionDataArgs["symbol"];
uri: UpdateSharesMetadataInstructionDataArgs["uri"];
}

export function getUpdateSharesMetadataInstruction<TAccountAdminAuthority extends string, TAccountStrategy extends string, TAccountGlobalConfig extends string, TAccountSharesMint extends string, TAccountSharesMetadata extends string, TAccountSharesMintAuthority extends string, TAccountMetadataProgram extends string, TProgramAddress extends Address = typeof YVAULTS_PROGRAM_ADDRESS>(input: UpdateSharesMetadataInput<TAccountAdminAuthority, TAccountStrategy, TAccountGlobalConfig, TAccountSharesMint, TAccountSharesMetadata, TAccountSharesMintAuthority, TAccountMetadataProgram>, config?: { programAddress?: TProgramAddress } ): UpdateSharesMetadataInstruction<TProgramAddress, TAccountAdminAuthority, TAccountStrategy, TAccountGlobalConfig, TAccountSharesMint, TAccountSharesMetadata, TAccountSharesMintAuthority, TAccountMetadataProgram> {
  // Program address.
const programAddress = config?.programAddress ?? YVAULTS_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { adminAuthority: { value: input.adminAuthority ?? null, isWritable: true }, strategy: { value: input.strategy ?? null, isWritable: false }, globalConfig: { value: input.globalConfig ?? null, isWritable: false }, sharesMint: { value: input.sharesMint ?? null, isWritable: false }, sharesMetadata: { value: input.sharesMetadata ?? null, isWritable: true }, sharesMintAuthority: { value: input.sharesMintAuthority ?? null, isWritable: false }, metadataProgram: { value: input.metadataProgram ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };




const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta("adminAuthority", accounts.adminAuthority), getAccountMeta("strategy", accounts.strategy), getAccountMeta("globalConfig", accounts.globalConfig), getAccountMeta("sharesMint", accounts.sharesMint), getAccountMeta("sharesMetadata", accounts.sharesMetadata), getAccountMeta("sharesMintAuthority", accounts.sharesMintAuthority), getAccountMeta("metadataProgram", accounts.metadataProgram)], data: getUpdateSharesMetadataInstructionDataEncoder().encode(args as UpdateSharesMetadataInstructionDataArgs), programAddress } as UpdateSharesMetadataInstruction<TProgramAddress, TAccountAdminAuthority, TAccountStrategy, TAccountGlobalConfig, TAccountSharesMint, TAccountSharesMetadata, TAccountSharesMintAuthority, TAccountMetadataProgram>);
}

export type ParsedUpdateSharesMetadataInstruction<TProgram extends string = typeof YVAULTS_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
adminAuthority: TAccountMetas[0];
strategy: TAccountMetas[1];
globalConfig: TAccountMetas[2];
sharesMint: TAccountMetas[3];
sharesMetadata: TAccountMetas[4];
sharesMintAuthority: TAccountMetas[5];
metadataProgram: TAccountMetas[6];
};
data: UpdateSharesMetadataInstructionData; };

export function parseUpdateSharesMetadataInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedUpdateSharesMetadataInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
  throw new Error(`Program client error: ${JSON.stringify({ actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 7 })}`);
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { adminAuthority: getNextAccount(), strategy: getNextAccount(), globalConfig: getNextAccount(), sharesMint: getNextAccount(), sharesMetadata: getNextAccount(), sharesMintAuthority: getNextAccount(), metadataProgram: getNextAccount() }, data: getUpdateSharesMetadataInstructionDataDecoder().decode(instruction.data) };
}