/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { assertAccountExists, assertAccountsExist, combineCodec, decodeAccount, fetchEncodedAccount, fetchEncodedAccounts, fixDecoderSize, fixEncoderSize, getAddressDecoder, getAddressEncoder, getArrayDecoder, getArrayEncoder, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, transformEncoder, type Account, type Address, type EncodedAccount, type FetchAccountConfig, type FetchAccountsConfig, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type MaybeAccount, type MaybeEncodedAccount, type ReadonlyUint8Array } from '@solana/kit';

export const TICK_ARRAY_BITMAP_EXTENSION_DISCRIMINATOR = new Uint8Array([60, 150, 36, 219, 97, 128, 139, 153]);

export function getTickArrayBitmapExtensionDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(TICK_ARRAY_BITMAP_EXTENSION_DISCRIMINATOR); }

export type TickArrayBitmapExtension = { discriminator: ReadonlyUint8Array; poolId: Address; positiveTickArrayBitmap: Array<Array<bigint>>; negativeTickArrayBitmap: Array<Array<bigint>>;  };

export type TickArrayBitmapExtensionArgs = { poolId: Address; positiveTickArrayBitmap: Array<Array<number | bigint>>; negativeTickArrayBitmap: Array<Array<number | bigint>>;  };

/** Gets the encoder for {@link TickArrayBitmapExtensionArgs} account data. */
export function getTickArrayBitmapExtensionEncoder(): FixedSizeEncoder<TickArrayBitmapExtensionArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['poolId', getAddressEncoder()], ['positiveTickArrayBitmap', getArrayEncoder(getArrayEncoder(getU64Encoder(), { size: 8 }), { size: 14 })], ['negativeTickArrayBitmap', getArrayEncoder(getArrayEncoder(getU64Encoder(), { size: 8 }), { size: 14 })]]), (value) => ({ ...value, discriminator: TICK_ARRAY_BITMAP_EXTENSION_DISCRIMINATOR }));
}

/** Gets the decoder for {@link TickArrayBitmapExtension} account data. */
export function getTickArrayBitmapExtensionDecoder(): FixedSizeDecoder<TickArrayBitmapExtension> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['poolId', getAddressDecoder()], ['positiveTickArrayBitmap', getArrayDecoder(getArrayDecoder(getU64Decoder(), { size: 8 }), { size: 14 })], ['negativeTickArrayBitmap', getArrayDecoder(getArrayDecoder(getU64Decoder(), { size: 8 }), { size: 14 })]]);
}

/** Gets the codec for {@link TickArrayBitmapExtension} account data. */
export function getTickArrayBitmapExtensionCodec(): FixedSizeCodec<TickArrayBitmapExtensionArgs, TickArrayBitmapExtension> {
    return combineCodec(getTickArrayBitmapExtensionEncoder(), getTickArrayBitmapExtensionDecoder());
}

export function decodeTickArrayBitmapExtension<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress>): Account<TickArrayBitmapExtension, TAddress>;
export function decodeTickArrayBitmapExtension<TAddress extends string = string>(encodedAccount: MaybeEncodedAccount<TAddress>): MaybeAccount<TickArrayBitmapExtension, TAddress>;
export function decodeTickArrayBitmapExtension<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>): Account<TickArrayBitmapExtension, TAddress> | MaybeAccount<TickArrayBitmapExtension, TAddress> {
  return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getTickArrayBitmapExtensionDecoder());
}

export async function fetchTickArrayBitmapExtension<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<TickArrayBitmapExtension, TAddress>> {
  const maybeAccount = await fetchMaybeTickArrayBitmapExtension(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTickArrayBitmapExtension<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<TickArrayBitmapExtension, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTickArrayBitmapExtension(maybeAccount);
}

export async function fetchAllTickArrayBitmapExtension(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<TickArrayBitmapExtension>[]> {
  const maybeAccounts = await fetchAllMaybeTickArrayBitmapExtension(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTickArrayBitmapExtension(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<TickArrayBitmapExtension>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeTickArrayBitmapExtension(maybeAccount));
}

export function getTickArrayBitmapExtensionSize(): number {
  return 1832;
}