/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getI32Decoder, getI32Encoder, getStructDecoder, getStructEncoder, getU16Decoder, getU16Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export type BinLiquidityDistributionByWeight = { 
/** Define the bin ID wish to deposit to. */
binId: number; 
/** weight of liquidity distributed for this bin id */
weight: number;  };

export type BinLiquidityDistributionByWeightArgs = BinLiquidityDistributionByWeight;

export function getBinLiquidityDistributionByWeightEncoder(): FixedSizeEncoder<BinLiquidityDistributionByWeightArgs> {
    return getStructEncoder([['binId', getI32Encoder()], ['weight', getU16Encoder()]]);
}

export function getBinLiquidityDistributionByWeightDecoder(): FixedSizeDecoder<BinLiquidityDistributionByWeight> {
    return getStructDecoder([['binId', getI32Decoder()], ['weight', getU16Decoder()]]);
}

export function getBinLiquidityDistributionByWeightCodec(): FixedSizeCodec<BinLiquidityDistributionByWeightArgs, BinLiquidityDistributionByWeight> {
    return combineCodec(getBinLiquidityDistributionByWeightEncoder(), getBinLiquidityDistributionByWeightDecoder());
}