/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getStructDecoder, getStructEncoder, getU128Decoder, getU128Encoder, getU64Decoder, getU64Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export type FeeInfo = { feeXPerTokenComplete: bigint; feeYPerTokenComplete: bigint; feeXPending: bigint; feeYPending: bigint;  };

export type FeeInfoArgs = { feeXPerTokenComplete: number | bigint; feeYPerTokenComplete: number | bigint; feeXPending: number | bigint; feeYPending: number | bigint;  };

export function getFeeInfoEncoder(): FixedSizeEncoder<FeeInfoArgs> {
    return getStructEncoder([['feeXPerTokenComplete', getU128Encoder()], ['feeYPerTokenComplete', getU128Encoder()], ['feeXPending', getU64Encoder()], ['feeYPending', getU64Encoder()]]);
}

export function getFeeInfoDecoder(): FixedSizeDecoder<FeeInfo> {
    return getStructDecoder([['feeXPerTokenComplete', getU128Decoder()], ['feeYPerTokenComplete', getU128Decoder()], ['feeXPending', getU64Decoder()], ['feeYPending', getU64Decoder()]]);
}

export function getFeeInfoCodec(): FixedSizeCodec<FeeInfoArgs, FeeInfo> {
    return combineCodec(getFeeInfoEncoder(), getFeeInfoDecoder());
}