/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export type ProtocolFee = { amountX: bigint; amountY: bigint;  };

export type ProtocolFeeArgs = { amountX: number | bigint; amountY: number | bigint;  };

export function getProtocolFeeEncoder(): FixedSizeEncoder<ProtocolFeeArgs> {
    return getStructEncoder([['amountX', getU64Encoder()], ['amountY', getU64Encoder()]]);
}

export function getProtocolFeeDecoder(): FixedSizeDecoder<ProtocolFee> {
    return getStructDecoder([['amountX', getU64Decoder()], ['amountY', getU64Decoder()]]);
}

export function getProtocolFeeCodec(): FixedSizeCodec<ProtocolFeeArgs, ProtocolFee> {
    return combineCodec(getProtocolFeeEncoder(), getProtocolFeeDecoder());
}