/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, getEnumDecoder, getEnumEncoder, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder } from '@solana/kit';

export enum StrategyType { SpotOneSide, CurveOneSide, BidAskOneSide, SpotBalanced, CurveBalanced, BidAskBalanced, SpotImBalanced, CurveImBalanced, BidAskImBalanced };

export type StrategyTypeArgs = StrategyType;

export function getStrategyTypeEncoder(): FixedSizeEncoder<StrategyTypeArgs> {
    return getEnumEncoder(StrategyType);
}

export function getStrategyTypeDecoder(): FixedSizeDecoder<StrategyType> {
    return getEnumDecoder(StrategyType);
}

export function getStrategyTypeCodec(): FixedSizeCodec<StrategyTypeArgs, StrategyType> {
    return combineCodec(getStrategyTypeEncoder(), getStrategyTypeDecoder());
}