/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getArrayDecoder, getArrayEncoder, getBytesDecoder, getBytesEncoder, getI32Decoder, getI32Encoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type Codec, type Decoder, type Encoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlySignerAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount } from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '../../_shims/programClientCore';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getBinLiquidityDistributionByWeightDecoder, getBinLiquidityDistributionByWeightEncoder, type BinLiquidityDistributionByWeight, type BinLiquidityDistributionByWeightArgs } from '../types';

const SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS = 7340032 as const;

export const ADD_LIQUIDITY_BY_WEIGHT_DISCRIMINATOR = new Uint8Array([28, 140, 238, 99, 231, 162, 21, 149]);

export function getAddLiquidityByWeightDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(ADD_LIQUIDITY_BY_WEIGHT_DISCRIMINATOR); }

export type AddLiquidityByWeightInstruction<TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS, TAccountPosition extends string | AccountMeta<string> = string, TAccountLbPair extends string | AccountMeta<string> = string, TAccountBinArrayBitmapExtension extends string | AccountMeta<string> = string, TAccountUserTokenX extends string | AccountMeta<string> = string, TAccountUserTokenY extends string | AccountMeta<string> = string, TAccountReserveX extends string | AccountMeta<string> = string, TAccountReserveY extends string | AccountMeta<string> = string, TAccountTokenXMint extends string | AccountMeta<string> = string, TAccountTokenYMint extends string | AccountMeta<string> = string, TAccountBinArrayLower extends string | AccountMeta<string> = string, TAccountBinArrayUpper extends string | AccountMeta<string> = string, TAccountSender extends string | AccountMeta<string> = string, TAccountTokenXProgram extends string | AccountMeta<string> = string, TAccountTokenYProgram extends string | AccountMeta<string> = string, TAccountEventAuthority extends string | AccountMeta<string> = string, TAccountProgram extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountPosition extends string ? WritableAccount<TAccountPosition> : TAccountPosition, TAccountLbPair extends string ? WritableAccount<TAccountLbPair> : TAccountLbPair, TAccountBinArrayBitmapExtension extends string ? WritableAccount<TAccountBinArrayBitmapExtension> : TAccountBinArrayBitmapExtension, TAccountUserTokenX extends string ? WritableAccount<TAccountUserTokenX> : TAccountUserTokenX, TAccountUserTokenY extends string ? WritableAccount<TAccountUserTokenY> : TAccountUserTokenY, TAccountReserveX extends string ? WritableAccount<TAccountReserveX> : TAccountReserveX, TAccountReserveY extends string ? WritableAccount<TAccountReserveY> : TAccountReserveY, TAccountTokenXMint extends string ? ReadonlyAccount<TAccountTokenXMint> : TAccountTokenXMint, TAccountTokenYMint extends string ? ReadonlyAccount<TAccountTokenYMint> : TAccountTokenYMint, TAccountBinArrayLower extends string ? WritableAccount<TAccountBinArrayLower> : TAccountBinArrayLower, TAccountBinArrayUpper extends string ? WritableAccount<TAccountBinArrayUpper> : TAccountBinArrayUpper, TAccountSender extends string ? ReadonlySignerAccount<TAccountSender> & AccountSignerMeta<TAccountSender> : TAccountSender, TAccountTokenXProgram extends string ? ReadonlyAccount<TAccountTokenXProgram> : TAccountTokenXProgram, TAccountTokenYProgram extends string ? ReadonlyAccount<TAccountTokenYProgram> : TAccountTokenYProgram, TAccountEventAuthority extends string ? ReadonlyAccount<TAccountEventAuthority> : TAccountEventAuthority, TAccountProgram extends string ? ReadonlyAccount<TAccountProgram> : TAccountProgram, ...TRemainingAccounts]>;

export type AddLiquidityByWeightInstructionData = { discriminator: ReadonlyUint8Array; 
/** Amount of X token to deposit */
amountX: bigint; 
/** Amount of Y token to deposit */
amountY: bigint; 
/** Active bin that integrator observe off-chain */
activeId: number; 
/** max active bin slippage allowed */
maxActiveBinSlippage: number; 
/** Liquidity distribution to each bins */
binLiquidityDist: Array<BinLiquidityDistributionByWeight>;  };

export type AddLiquidityByWeightInstructionDataArgs = { 
/** Amount of X token to deposit */
amountX: number | bigint; 
/** Amount of Y token to deposit */
amountY: number | bigint; 
/** Active bin that integrator observe off-chain */
activeId: number; 
/** max active bin slippage allowed */
maxActiveBinSlippage: number; 
/** Liquidity distribution to each bins */
binLiquidityDist: Array<BinLiquidityDistributionByWeightArgs>;  };

export function getAddLiquidityByWeightInstructionDataEncoder(): Encoder<AddLiquidityByWeightInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['amountX', getU64Encoder()], ['amountY', getU64Encoder()], ['activeId', getI32Encoder()], ['maxActiveBinSlippage', getI32Encoder()], ['binLiquidityDist', getArrayEncoder(getBinLiquidityDistributionByWeightEncoder())]]), (value) => ({ ...value, discriminator: ADD_LIQUIDITY_BY_WEIGHT_DISCRIMINATOR }));
}

export function getAddLiquidityByWeightInstructionDataDecoder(): Decoder<AddLiquidityByWeightInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['amountX', getU64Decoder()], ['amountY', getU64Decoder()], ['activeId', getI32Decoder()], ['maxActiveBinSlippage', getI32Decoder()], ['binLiquidityDist', getArrayDecoder(getBinLiquidityDistributionByWeightDecoder())]]);
}

export function getAddLiquidityByWeightInstructionDataCodec(): Codec<AddLiquidityByWeightInstructionDataArgs, AddLiquidityByWeightInstructionData> {
    return combineCodec(getAddLiquidityByWeightInstructionDataEncoder(), getAddLiquidityByWeightInstructionDataDecoder());
}

export type AddLiquidityByWeightInput<TAccountPosition extends string = string, TAccountLbPair extends string = string, TAccountBinArrayBitmapExtension extends string = string, TAccountUserTokenX extends string = string, TAccountUserTokenY extends string = string, TAccountReserveX extends string = string, TAccountReserveY extends string = string, TAccountTokenXMint extends string = string, TAccountTokenYMint extends string = string, TAccountBinArrayLower extends string = string, TAccountBinArrayUpper extends string = string, TAccountSender extends string = string, TAccountTokenXProgram extends string = string, TAccountTokenYProgram extends string = string, TAccountEventAuthority extends string = string, TAccountProgram extends string = string> =  {
  position: Address<TAccountPosition>;
lbPair: Address<TAccountLbPair>;
binArrayBitmapExtension?: Address<TAccountBinArrayBitmapExtension>;
userTokenX: Address<TAccountUserTokenX>;
userTokenY: Address<TAccountUserTokenY>;
reserveX: Address<TAccountReserveX>;
reserveY: Address<TAccountReserveY>;
tokenXMint: Address<TAccountTokenXMint>;
tokenYMint: Address<TAccountTokenYMint>;
binArrayLower: Address<TAccountBinArrayLower>;
binArrayUpper: Address<TAccountBinArrayUpper>;
sender: TransactionSigner<TAccountSender>;
tokenXProgram: Address<TAccountTokenXProgram>;
tokenYProgram: Address<TAccountTokenYProgram>;
eventAuthority: Address<TAccountEventAuthority>;
program: Address<TAccountProgram>;
amountX: AddLiquidityByWeightInstructionDataArgs["amountX"];
amountY: AddLiquidityByWeightInstructionDataArgs["amountY"];
activeId: AddLiquidityByWeightInstructionDataArgs["activeId"];
maxActiveBinSlippage: AddLiquidityByWeightInstructionDataArgs["maxActiveBinSlippage"];
binLiquidityDist: AddLiquidityByWeightInstructionDataArgs["binLiquidityDist"];
}

export function getAddLiquidityByWeightInstruction<TAccountPosition extends string, TAccountLbPair extends string, TAccountBinArrayBitmapExtension extends string, TAccountUserTokenX extends string, TAccountUserTokenY extends string, TAccountReserveX extends string, TAccountReserveY extends string, TAccountTokenXMint extends string, TAccountTokenYMint extends string, TAccountBinArrayLower extends string, TAccountBinArrayUpper extends string, TAccountSender extends string, TAccountTokenXProgram extends string, TAccountTokenYProgram extends string, TAccountEventAuthority extends string, TAccountProgram extends string, TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS>(input: AddLiquidityByWeightInput<TAccountPosition, TAccountLbPair, TAccountBinArrayBitmapExtension, TAccountUserTokenX, TAccountUserTokenY, TAccountReserveX, TAccountReserveY, TAccountTokenXMint, TAccountTokenYMint, TAccountBinArrayLower, TAccountBinArrayUpper, TAccountSender, TAccountTokenXProgram, TAccountTokenYProgram, TAccountEventAuthority, TAccountProgram>, config?: { programAddress?: TProgramAddress } ): AddLiquidityByWeightInstruction<TProgramAddress, TAccountPosition, TAccountLbPair, TAccountBinArrayBitmapExtension, TAccountUserTokenX, TAccountUserTokenY, TAccountReserveX, TAccountReserveY, TAccountTokenXMint, TAccountTokenYMint, TAccountBinArrayLower, TAccountBinArrayUpper, TAccountSender, TAccountTokenXProgram, TAccountTokenYProgram, TAccountEventAuthority, TAccountProgram> {
  // Program address.
const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { position: { value: input.position ?? null, isWritable: true }, lbPair: { value: input.lbPair ?? null, isWritable: true }, binArrayBitmapExtension: { value: input.binArrayBitmapExtension ?? null, isWritable: true }, userTokenX: { value: input.userTokenX ?? null, isWritable: true }, userTokenY: { value: input.userTokenY ?? null, isWritable: true }, reserveX: { value: input.reserveX ?? null, isWritable: true }, reserveY: { value: input.reserveY ?? null, isWritable: true }, tokenXMint: { value: input.tokenXMint ?? null, isWritable: false }, tokenYMint: { value: input.tokenYMint ?? null, isWritable: false }, binArrayLower: { value: input.binArrayLower ?? null, isWritable: true }, binArrayUpper: { value: input.binArrayUpper ?? null, isWritable: true }, sender: { value: input.sender ?? null, isWritable: false }, tokenXProgram: { value: input.tokenXProgram ?? null, isWritable: false }, tokenYProgram: { value: input.tokenYProgram ?? null, isWritable: false }, eventAuthority: { value: input.eventAuthority ?? null, isWritable: false }, program: { value: input.program ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };




const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta("position", accounts.position), getAccountMeta("lbPair", accounts.lbPair), getAccountMeta("binArrayBitmapExtension", accounts.binArrayBitmapExtension), getAccountMeta("userTokenX", accounts.userTokenX), getAccountMeta("userTokenY", accounts.userTokenY), getAccountMeta("reserveX", accounts.reserveX), getAccountMeta("reserveY", accounts.reserveY), getAccountMeta("tokenXMint", accounts.tokenXMint), getAccountMeta("tokenYMint", accounts.tokenYMint), getAccountMeta("binArrayLower", accounts.binArrayLower), getAccountMeta("binArrayUpper", accounts.binArrayUpper), getAccountMeta("sender", accounts.sender), getAccountMeta("tokenXProgram", accounts.tokenXProgram), getAccountMeta("tokenYProgram", accounts.tokenYProgram), getAccountMeta("eventAuthority", accounts.eventAuthority), getAccountMeta("program", accounts.program)], data: getAddLiquidityByWeightInstructionDataEncoder().encode(args as AddLiquidityByWeightInstructionDataArgs), programAddress } as AddLiquidityByWeightInstruction<TProgramAddress, TAccountPosition, TAccountLbPair, TAccountBinArrayBitmapExtension, TAccountUserTokenX, TAccountUserTokenY, TAccountReserveX, TAccountReserveY, TAccountTokenXMint, TAccountTokenYMint, TAccountBinArrayLower, TAccountBinArrayUpper, TAccountSender, TAccountTokenXProgram, TAccountTokenYProgram, TAccountEventAuthority, TAccountProgram>);
}

export type ParsedAddLiquidityByWeightInstruction<TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
position: TAccountMetas[0];
lbPair: TAccountMetas[1];
binArrayBitmapExtension?: TAccountMetas[2] | undefined;
userTokenX: TAccountMetas[3];
userTokenY: TAccountMetas[4];
reserveX: TAccountMetas[5];
reserveY: TAccountMetas[6];
tokenXMint: TAccountMetas[7];
tokenYMint: TAccountMetas[8];
binArrayLower: TAccountMetas[9];
binArrayUpper: TAccountMetas[10];
sender: TAccountMetas[11];
tokenXProgram: TAccountMetas[12];
tokenYProgram: TAccountMetas[13];
eventAuthority: TAccountMetas[14];
program: TAccountMetas[15];
};
data: AddLiquidityByWeightInstructionData; };

export function parseAddLiquidityByWeightInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedAddLiquidityByWeightInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 16) {
  throw new Error(`Program client error: ${JSON.stringify({ actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 16 })}`);
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
const getNextOptionalAccount = () => {
  const accountMeta = getNextAccount();
  return accountMeta.address === LB_CLMM_PROGRAM_ADDRESS ? undefined : accountMeta;
};
  return { programAddress: instruction.programAddress, accounts: { position: getNextAccount(), lbPair: getNextAccount(), binArrayBitmapExtension: getNextOptionalAccount(), userTokenX: getNextAccount(), userTokenY: getNextAccount(), reserveX: getNextAccount(), reserveY: getNextAccount(), tokenXMint: getNextAccount(), tokenYMint: getNextAccount(), binArrayLower: getNextAccount(), binArrayUpper: getNextAccount(), sender: getNextAccount(), tokenXProgram: getNextAccount(), tokenYProgram: getNextAccount(), eventAuthority: getNextAccount(), program: getNextAccount() }, data: getAddLiquidityByWeightInstructionDataDecoder().decode(instruction.data) };
}