/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '../../_shims/programClientCore';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';

const SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS = 7340032 as const;

export const SET_ACTIVATION_SLOT_DISCRIMINATOR = new Uint8Array([200, 227, 90, 83, 27, 79, 191, 88]);

export function getSetActivationSlotDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(SET_ACTIVATION_SLOT_DISCRIMINATOR); }

export type SetActivationSlotInstruction<TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS, TAccountLbPair extends string | AccountMeta<string> = string, TAccountAdmin extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountLbPair extends string ? WritableAccount<TAccountLbPair> : TAccountLbPair, TAccountAdmin extends string ? WritableSignerAccount<TAccountAdmin> & AccountSignerMeta<TAccountAdmin> : TAccountAdmin, ...TRemainingAccounts]>;

export type SetActivationSlotInstructionData = { discriminator: ReadonlyUint8Array; activationSlot: bigint;  };

export type SetActivationSlotInstructionDataArgs = { activationSlot: number | bigint;  };

export function getSetActivationSlotInstructionDataEncoder(): FixedSizeEncoder<SetActivationSlotInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['activationSlot', getU64Encoder()]]), (value) => ({ ...value, discriminator: SET_ACTIVATION_SLOT_DISCRIMINATOR }));
}

export function getSetActivationSlotInstructionDataDecoder(): FixedSizeDecoder<SetActivationSlotInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['activationSlot', getU64Decoder()]]);
}

export function getSetActivationSlotInstructionDataCodec(): FixedSizeCodec<SetActivationSlotInstructionDataArgs, SetActivationSlotInstructionData> {
    return combineCodec(getSetActivationSlotInstructionDataEncoder(), getSetActivationSlotInstructionDataDecoder());
}

export type SetActivationSlotInput<TAccountLbPair extends string = string, TAccountAdmin extends string = string> =  {
  lbPair: Address<TAccountLbPair>;
admin: TransactionSigner<TAccountAdmin>;
activationSlot: SetActivationSlotInstructionDataArgs["activationSlot"];
}

export function getSetActivationSlotInstruction<TAccountLbPair extends string, TAccountAdmin extends string, TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS>(input: SetActivationSlotInput<TAccountLbPair, TAccountAdmin>, config?: { programAddress?: TProgramAddress } ): SetActivationSlotInstruction<TProgramAddress, TAccountLbPair, TAccountAdmin> {
  // Program address.
const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { lbPair: { value: input.lbPair ?? null, isWritable: true }, admin: { value: input.admin ?? null, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };




const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta("lbPair", accounts.lbPair), getAccountMeta("admin", accounts.admin)], data: getSetActivationSlotInstructionDataEncoder().encode(args as SetActivationSlotInstructionDataArgs), programAddress } as SetActivationSlotInstruction<TProgramAddress, TAccountLbPair, TAccountAdmin>);
}

export type ParsedSetActivationSlotInstruction<TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
lbPair: TAccountMetas[0];
admin: TAccountMetas[1];
};
data: SetActivationSlotInstructionData; };

export function parseSetActivationSlotInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedSetActivationSlotInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
  throw new Error(`Program client error: ${JSON.stringify({ actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 2 })}`);
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { lbPair: getNextAccount(), admin: getNextAccount() }, data: getSetActivationSlotInstructionDataDecoder().decode(instruction.data) };
}