/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlySignerAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount } from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_REWARD_DURATION_DISCRIMINATOR = new Uint8Array([138, 174, 196, 169, 213, 235, 254, 107]);

export function getUpdateRewardDurationDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(UPDATE_REWARD_DURATION_DISCRIMINATOR); }

export type UpdateRewardDurationInstruction<TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS, TAccountLbPair extends string | AccountMeta<string> = string, TAccountAdmin extends string | AccountMeta<string> = string, TAccountBinArray extends string | AccountMeta<string> = string, TAccountEventAuthority extends string | AccountMeta<string> = string, TAccountProgram extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountLbPair extends string ? WritableAccount<TAccountLbPair> : TAccountLbPair, TAccountAdmin extends string ? ReadonlySignerAccount<TAccountAdmin> & AccountSignerMeta<TAccountAdmin> : TAccountAdmin, TAccountBinArray extends string ? WritableAccount<TAccountBinArray> : TAccountBinArray, TAccountEventAuthority extends string ? ReadonlyAccount<TAccountEventAuthority> : TAccountEventAuthority, TAccountProgram extends string ? ReadonlyAccount<TAccountProgram> : TAccountProgram, ...TRemainingAccounts]>;

export type UpdateRewardDurationInstructionData = { discriminator: ReadonlyUint8Array; rewardIndex: bigint; newDuration: bigint;  };

export type UpdateRewardDurationInstructionDataArgs = { rewardIndex: number | bigint; newDuration: number | bigint;  };

export function getUpdateRewardDurationInstructionDataEncoder(): FixedSizeEncoder<UpdateRewardDurationInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['rewardIndex', getU64Encoder()], ['newDuration', getU64Encoder()]]), (value) => ({ ...value, discriminator: UPDATE_REWARD_DURATION_DISCRIMINATOR }));
}

export function getUpdateRewardDurationInstructionDataDecoder(): FixedSizeDecoder<UpdateRewardDurationInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['rewardIndex', getU64Decoder()], ['newDuration', getU64Decoder()]]);
}

export function getUpdateRewardDurationInstructionDataCodec(): FixedSizeCodec<UpdateRewardDurationInstructionDataArgs, UpdateRewardDurationInstructionData> {
    return combineCodec(getUpdateRewardDurationInstructionDataEncoder(), getUpdateRewardDurationInstructionDataDecoder());
}

export type UpdateRewardDurationInput<TAccountLbPair extends string = string, TAccountAdmin extends string = string, TAccountBinArray extends string = string, TAccountEventAuthority extends string = string, TAccountProgram extends string = string> =  {
  lbPair: Address<TAccountLbPair>;
admin: TransactionSigner<TAccountAdmin>;
binArray: Address<TAccountBinArray>;
eventAuthority: Address<TAccountEventAuthority>;
program: Address<TAccountProgram>;
rewardIndex: UpdateRewardDurationInstructionDataArgs["rewardIndex"];
newDuration: UpdateRewardDurationInstructionDataArgs["newDuration"];
}

export function getUpdateRewardDurationInstruction<TAccountLbPair extends string, TAccountAdmin extends string, TAccountBinArray extends string, TAccountEventAuthority extends string, TAccountProgram extends string, TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS>(input: UpdateRewardDurationInput<TAccountLbPair, TAccountAdmin, TAccountBinArray, TAccountEventAuthority, TAccountProgram>, config?: { programAddress?: TProgramAddress } ): UpdateRewardDurationInstruction<TProgramAddress, TAccountLbPair, TAccountAdmin, TAccountBinArray, TAccountEventAuthority, TAccountProgram> {
  // Program address.
const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { lbPair: { value: input.lbPair ?? null, isWritable: true }, admin: { value: input.admin ?? null, isWritable: false }, binArray: { value: input.binArray ?? null, isWritable: true }, eventAuthority: { value: input.eventAuthority ?? null, isWritable: false }, program: { value: input.program ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>;


// Original args.
const args = { ...input,  };




const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta(accounts.lbPair), getAccountMeta(accounts.admin), getAccountMeta(accounts.binArray), getAccountMeta(accounts.eventAuthority), getAccountMeta(accounts.program)], data: getUpdateRewardDurationInstructionDataEncoder().encode(args as UpdateRewardDurationInstructionDataArgs), programAddress } as UpdateRewardDurationInstruction<TProgramAddress, TAccountLbPair, TAccountAdmin, TAccountBinArray, TAccountEventAuthority, TAccountProgram>);
}

export type ParsedUpdateRewardDurationInstruction<TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
lbPair: TAccountMetas[0];
admin: TAccountMetas[1];
binArray: TAccountMetas[2];
eventAuthority: TAccountMetas[3];
program: TAccountMetas[4];
};
data: UpdateRewardDurationInstructionData; };

export function parseUpdateRewardDurationInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedUpdateRewardDurationInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
  // TODO: Coded error.
  throw new Error('Not enough accounts');
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { lbPair: getNextAccount(), admin: getNextAccount(), binArray: getNextAccount(), eventAuthority: getNextAccount(), program: getNextAccount() }, data: getUpdateRewardDurationInstructionDataDecoder().decode(instruction.data) };
}