/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '../../_shims/programClientCore';
import { AMM_V3_PROGRAM_ADDRESS } from '../programs';

const SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS = 7340032 as const;

export const CLOSE_POSITION_DISCRIMINATOR = new Uint8Array([123, 134, 81, 0, 49, 68, 98, 98]);

export function getClosePositionDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_POSITION_DISCRIMINATOR); }

export type ClosePositionInstruction<TProgram extends string = typeof AMM_V3_PROGRAM_ADDRESS, TAccountNftOwner extends string | AccountMeta<string> = string, TAccountPositionNftMint extends string | AccountMeta<string> = string, TAccountPositionNftAccount extends string | AccountMeta<string> = string, TAccountPersonalPosition extends string | AccountMeta<string> = string, TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111", TAccountTokenProgram extends string | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountNftOwner extends string ? WritableSignerAccount<TAccountNftOwner> & AccountSignerMeta<TAccountNftOwner> : TAccountNftOwner, TAccountPositionNftMint extends string ? WritableAccount<TAccountPositionNftMint> : TAccountPositionNftMint, TAccountPositionNftAccount extends string ? WritableAccount<TAccountPositionNftAccount> : TAccountPositionNftAccount, TAccountPersonalPosition extends string ? WritableAccount<TAccountPersonalPosition> : TAccountPersonalPosition, TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram, TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram, ...TRemainingAccounts]>;

export type ClosePositionInstructionData = { discriminator: ReadonlyUint8Array;  };

export type ClosePositionInstructionDataArgs = {  };

export function getClosePositionInstructionDataEncoder(): FixedSizeEncoder<ClosePositionInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]), (value) => ({ ...value, discriminator: CLOSE_POSITION_DISCRIMINATOR }));
}

export function getClosePositionInstructionDataDecoder(): FixedSizeDecoder<ClosePositionInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getClosePositionInstructionDataCodec(): FixedSizeCodec<ClosePositionInstructionDataArgs, ClosePositionInstructionData> {
    return combineCodec(getClosePositionInstructionDataEncoder(), getClosePositionInstructionDataDecoder());
}

export type ClosePositionInput<TAccountNftOwner extends string = string, TAccountPositionNftMint extends string = string, TAccountPositionNftAccount extends string = string, TAccountPersonalPosition extends string = string, TAccountSystemProgram extends string = string, TAccountTokenProgram extends string = string> =  {
  nftOwner: TransactionSigner<TAccountNftOwner>;
positionNftMint: Address<TAccountPositionNftMint>;
positionNftAccount: Address<TAccountPositionNftAccount>;
personalPosition: Address<TAccountPersonalPosition>;
systemProgram?: Address<TAccountSystemProgram>;
tokenProgram?: Address<TAccountTokenProgram>;
}

export function getClosePositionInstruction<TAccountNftOwner extends string, TAccountPositionNftMint extends string, TAccountPositionNftAccount extends string, TAccountPersonalPosition extends string, TAccountSystemProgram extends string, TAccountTokenProgram extends string, TProgramAddress extends Address = typeof AMM_V3_PROGRAM_ADDRESS>(input: ClosePositionInput<TAccountNftOwner, TAccountPositionNftMint, TAccountPositionNftAccount, TAccountPersonalPosition, TAccountSystemProgram, TAccountTokenProgram>, config?: { programAddress?: TProgramAddress } ): ClosePositionInstruction<TProgramAddress, TAccountNftOwner, TAccountPositionNftMint, TAccountPositionNftAccount, TAccountPersonalPosition, TAccountSystemProgram, TAccountTokenProgram> {
  // Program address.
const programAddress = config?.programAddress ?? AMM_V3_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { nftOwner: { value: input.nftOwner ?? null, isWritable: true }, positionNftMint: { value: input.positionNftMint ?? null, isWritable: true }, positionNftAccount: { value: input.positionNftAccount ?? null, isWritable: true }, personalPosition: { value: input.personalPosition ?? null, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isWritable: false }, tokenProgram: { value: input.tokenProgram ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Resolve default values.
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}
if (!accounts.tokenProgram.value) {
accounts.tokenProgram.value = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
}

const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta("nftOwner", accounts.nftOwner), getAccountMeta("positionNftMint", accounts.positionNftMint), getAccountMeta("positionNftAccount", accounts.positionNftAccount), getAccountMeta("personalPosition", accounts.personalPosition), getAccountMeta("systemProgram", accounts.systemProgram), getAccountMeta("tokenProgram", accounts.tokenProgram)], data: getClosePositionInstructionDataEncoder().encode({}), programAddress } as ClosePositionInstruction<TProgramAddress, TAccountNftOwner, TAccountPositionNftMint, TAccountPositionNftAccount, TAccountPersonalPosition, TAccountSystemProgram, TAccountTokenProgram>);
}

export type ParsedClosePositionInstruction<TProgram extends string = typeof AMM_V3_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
nftOwner: TAccountMetas[0];
positionNftMint: TAccountMetas[1];
positionNftAccount: TAccountMetas[2];
personalPosition: TAccountMetas[3];
systemProgram: TAccountMetas[4];
tokenProgram: TAccountMetas[5];
};
data: ClosePositionInstructionData; };

export function parseClosePositionInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedClosePositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
  throw new Error(`Program client error: ${JSON.stringify({ actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 6 })}`);
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { nftOwner: getNextAccount(), positionNftMint: getNextAccount(), positionNftAccount: getNextAccount(), personalPosition: getNextAccount(), systemProgram: getNextAccount(), tokenProgram: getNextAccount() }, data: getClosePositionInstructionDataDecoder().decode(instruction.data) };
}