/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getAddressDecoder, getAddressEncoder, getArrayDecoder, getArrayEncoder, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU8Decoder, getU8Encoder, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type Codec, type Decoder, type Encoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlySignerAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount } from '@solana/kit';
import { AMM_V3_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_OPERATION_ACCOUNT_DISCRIMINATOR = new Uint8Array([127, 70, 119, 40, 188, 227, 61, 7]);

export function getUpdateOperationAccountDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(UPDATE_OPERATION_ACCOUNT_DISCRIMINATOR); }

export type UpdateOperationAccountInstruction<TProgram extends string = typeof AMM_V3_PROGRAM_ADDRESS, TAccountOwner extends string | AccountMeta<string> = string, TAccountOperationState extends string | AccountMeta<string> = string, TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountOwner extends string ? ReadonlySignerAccount<TAccountOwner> & AccountSignerMeta<TAccountOwner> : TAccountOwner, TAccountOperationState extends string ? WritableAccount<TAccountOperationState> : TAccountOperationState, TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram, ...TRemainingAccounts]>;

export type UpdateOperationAccountInstructionData = { discriminator: ReadonlyUint8Array; param: number; keys: Array<Address>;  };

export type UpdateOperationAccountInstructionDataArgs = { param: number; keys: Array<Address>;  };

export function getUpdateOperationAccountInstructionDataEncoder(): Encoder<UpdateOperationAccountInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['param', getU8Encoder()], ['keys', getArrayEncoder(getAddressEncoder())]]), (value) => ({ ...value, discriminator: UPDATE_OPERATION_ACCOUNT_DISCRIMINATOR }));
}

export function getUpdateOperationAccountInstructionDataDecoder(): Decoder<UpdateOperationAccountInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['param', getU8Decoder()], ['keys', getArrayDecoder(getAddressDecoder())]]);
}

export function getUpdateOperationAccountInstructionDataCodec(): Codec<UpdateOperationAccountInstructionDataArgs, UpdateOperationAccountInstructionData> {
    return combineCodec(getUpdateOperationAccountInstructionDataEncoder(), getUpdateOperationAccountInstructionDataDecoder());
}

export type UpdateOperationAccountInput<TAccountOwner extends string = string, TAccountOperationState extends string = string, TAccountSystemProgram extends string = string> =  {
  owner: TransactionSigner<TAccountOwner>;
operationState: Address<TAccountOperationState>;
systemProgram?: Address<TAccountSystemProgram>;
param: UpdateOperationAccountInstructionDataArgs["param"];
keys: UpdateOperationAccountInstructionDataArgs["keys"];
}

export function getUpdateOperationAccountInstruction<TAccountOwner extends string, TAccountOperationState extends string, TAccountSystemProgram extends string, TProgramAddress extends Address = typeof AMM_V3_PROGRAM_ADDRESS>(input: UpdateOperationAccountInput<TAccountOwner, TAccountOperationState, TAccountSystemProgram>, config?: { programAddress?: TProgramAddress } ): UpdateOperationAccountInstruction<TProgramAddress, TAccountOwner, TAccountOperationState, TAccountSystemProgram> {
  // Program address.
const programAddress = config?.programAddress ?? AMM_V3_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { owner: { value: input.owner ?? null, isWritable: false }, operationState: { value: input.operationState ?? null, isWritable: true }, systemProgram: { value: input.systemProgram ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.systemProgram.value) {
accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
}

const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta(accounts.owner), getAccountMeta(accounts.operationState), getAccountMeta(accounts.systemProgram)], data: getUpdateOperationAccountInstructionDataEncoder().encode(args as UpdateOperationAccountInstructionDataArgs), programAddress } as UpdateOperationAccountInstruction<TProgramAddress, TAccountOwner, TAccountOperationState, TAccountSystemProgram>);
}

export type ParsedUpdateOperationAccountInstruction<TProgram extends string = typeof AMM_V3_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
owner: TAccountMetas[0];
operationState: TAccountMetas[1];
systemProgram: TAccountMetas[2];
};
data: UpdateOperationAccountInstructionData; };

export function parseUpdateOperationAccountInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedUpdateOperationAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
  // TODO: Coded error.
  throw new Error('Not enough accounts');
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { owner: getNextAccount(), operationState: getNextAccount(), systemProgram: getNextAccount() }, data: getUpdateOperationAccountInstructionDataDecoder().decode(instruction.data) };
}